steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/springbootgc', '.']
images: ['gcr.io/$PROJECT_ID/springbootgc']